apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/sonitamuluh/pyhon-application
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
