# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
      - name: python-application-container
        image: python:1.1
        command: ["python", "-u", "python-application.py"]
        ports:
        - containerPort: 8080
