# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-application
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30032
  type: NodePort
