apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/sonitamengwi/python-argocd-deploymentt
    targetRevision: HEAD
    path: my-yaml-file
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:   
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
