# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python.py
spec:
  selector:
    matchLabels:
      app: python.py
  replicas: 3
  template:
    metadata:
      labels:
        app: python.py
    spec:
      containers:
      - name: python.py
        image: sonitamuluh/python.py:1.1
        ports:
        - containerPort: 8080


