# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python.py-service
spec:
  selector:
    app: python.py
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31000
  type: NodePort


